[[pages]]
name = "Trang Chá»§"
is_section = true
icon = "ğŸ "

[[pages]]
path = "home.py"
name = "Dashboard"
icon = ""

[[pages]]
name = "API Key"
is_section = true
icon = "ğŸ”‘"

[[pages]]
path = "API_key.py"
name = "HÆ°á»›ng dáº«n láº¥y API KEY"
icon = ""

[[pages]]
name = "Overview"
is_section = true
icon = "ğŸ“‘"

[[pages]]
path = "overview.py"
name = "Data Report"
icon = ""


[[pages]]
name = "CÃ¡c Chá»©c NÄƒng cá»§a LIDA"
is_section = true
icon = "ğŸ“Š"

[[pages]]
path = "task.py"
name = "LIDA Tasks"
icon = ""
